### ISSUE TITLE
Duda en Tarea 2

### ISSUE THREAD

**Issue by sdroldan** [sbanchero/gee-curso-intro-js#1]
Hola Santiago,
En el "Módulo 0", Tarea 2, pide "Escriba un objeto que se llame __corrida__ que tenga dos atributos: 1) __pi__ con el valor 3.1416, 2) __azimuth__ con el valor 90 y 3) fechas una arreglo con las fecha 2021-05-01 y 2021-06-01. Imprima cada atributo por separado."
No queda claro si "fechas" debiera ser un tercer atributo del mismo objeto u otro objeto.

**Comment by sbanchero** [comment]
Hola Sergio
Ya corregí el enunciado.
Gracias por el aviso. 
Saludos
